# 로컬 환경
spring:
  profiles:
    active: local

  h2:
    console:
      enabled: true

  datasource:
    username: sa
    url: jdbc:h2:mem:db;MODE=MYSQL;
    password: ''

  jackson:
    serialization:
      fail-on-empty-beans: false

  # google 메일 발송
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ GOOGLE_ID }
    password: ${ GOOGLE_PW }
    properties:
      debug: true
      mail.smtp:
        auth: true
        starttls:
          enable: true

  # image upload limit
  servlet.multipart:
    maxFileSize: 10MB
    maxRequestSize: 10MB

  # redis
  redis:
    host: ${ REDIS_HOST }
    port: 6379

# s3
cloud.aws:
  stack.auto: false
  region.static: ap-northeast-2
  credentials:
    access-key: ${ ACCESS_KEY }
    secret-key: ${ SECRET_KEY }
    instance-profile: true
  s3.bucket: ${ S3_BUCKET }


# 환경변수
admin.token: {{ secrets.ADMIN_TOKEN }}

jwt.secret.key: ${ JWT_SECRET_KEY }

