# 로컬 환경
spring:
  profiles:
    active: local

  h2:
    console:
      enabled: true

  datasource:
    username: sa
    url: jdbc:h2:mem:db;MODE=MYSQL;
    password: ''

  jackson:
    serialization:
      fail-on-empty-beans: false

  # google 메일 발송
  mail:
    host: smtp.gmail.com
    port: 587
    username: {{ secrets.GOOGLE_ID }}
    password: {{ secrets.GOOGLE_PW }}
    properties:
      debug: true
      mail.smtp:
        auth: true
        starttls:
          enable: true

  # image upload limit
  servlet.multipart:
    maxFileSize: 5MB
    maxRequestSize: 5MB

  # redis
  redis:
    host: {{ secrets.REDIS_HOST }}
    port: 6379

# s3
cloud.aws:
  stack.auto: false
  region.static: ap-northeast-2
  credentials:
    access-key: {{ secrets.AWS_S3_ACCESS_KEY }}
    secret-key: {{ secrets.AWS_S3_SECRET_KEY }}
    instance-profile: true
  s3.bucket: {{ secrets.AWS_S3_BUCKET }}


# 환경변수
admin.token: {{ secrets.ADMIN_TOKEN }}

jwt.secret.key: {{ secrets.JWT_SECRET_KEY }}

