# 로컬 환경
spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${ RDS_URL }
    username: ${ RDS_ID }
    password: ${ RDS_PW }

  data:
    mongodb:
      uri: ${ MONGODB_URL }
      database: ${ MONGODB_DATABASE }

  # redis
  redis:
    host: ${ REDIS_HOST }
    port: 6379

  jackson:
    serialization:
      fail-on-empty-beans: false

  # google 메일 발송
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ GOOGLE_ID }
    password: ${ GOOGLE_PW }
    properties:
      debug: true
      mail.smtp:
        auth: true
        starttls:
          enable: true

  # image upload limit
  servlet.multipart:
    maxFileSize: 10MB
    maxRequestSize: 10MB

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# paramter store
aws:
  paramstore:
    name: pinme
    enabled: true


# s3
cloud:
  aws:
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: ${ ACCESS_KEY }
      secret-key: ${ SECRET_KEY }
      instance-profile: true
    s3.bucket: ${ S3_BUCKET }


# OAuth
OAuth2:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ${ GOOGLE_OAUTH2_CLIENT_ID }
    client-secret: ${ GOOGLE_OAUTH2_CLIENT_SECRET }
    callback-url: ${ GOOGLE_OAUTH2_CALLBACK_URL }
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile


# swaggerdoc
springdoc:
  version: v1.0.0
  packages-to-scan: com.gigajet.mhlb
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


# 환경변수
jwt.secret.key: ${ JWT_SECRET_KEY }

workspace.default.image: ${ WORKSPACE_DEFAULT_IMAGE }
user.default.image: ${ USER_DEFAULT_IMAGE }

aes.key: ${ AES_KEY }